{% set name = "nichord" %}
{% set version = "0.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nichord-{{ version }}.tar.gz
  sha256: e69f05af07e1271f7b0dec83c9923fd0c9c966db02eac7bdc1e17ec8c5fd0c47

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - nilearn
    - pandas
    - matplotlib-base
    - numpy
    - scipy
    - pillow

test:
  imports:
    - nichord
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/paulcbogdan/NiChord
  summary: Creates chord diagrams for connectivity/graph data
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - paulcbogdan
