{% set name = "nichord" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nichord-{{ version }}.tar.gz
  sha256: 50043ab3db12868b21ac0b7776b6565e0f2c5a56af12e1aadddbc80b0e5789c3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - nilearn
    - pandas
    - matplotlib-base
    - numpy
    - scipy
    - pillow

test:
  imports:
    - nichord
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/paulcbogdan/NiChord
  summary: Creates chord diagrams for connectivity/graph data
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - paulcbogdan
